# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iSCMEBCpp <- function(vList, Adjlist, yList_int, Mu_int, Sigma_int, Psi_int, beta_int, beta_grid, maxIter_ICM, maxIter, epsLogLik, verbose, homo, Sigma_equal, Sigma_diag, Sp_embed, maxK, minK, coreNum) {
    .Call(`_ProFAST_iSCMEBCpp`, vList, Adjlist, yList_int, Mu_int, Sigma_int, Psi_int, beta_int, beta_grid, maxIter_ICM, maxIter, epsLogLik, verbose, homo, Sigma_equal, Sigma_diag, Sp_embed, maxK, minK, coreNum)
}

getneighborhood_fast <- function(x, radius) {
    .Call(`_ProFAST_getneighborhood_fast`, x, radius)
}

wpcaCpp <- function(X, nPCs, weighted = TRUE) {
    .Call(`_ProFAST_wpcaCpp`, X, nPCs, weighted)
}

correct_one_gene <- function(Xlist, RList, HList, Tm, Adjlist, sigmaj_int, psij_int, alphaj_int, gammaj_int, zetaj_int, maxIter, epsELBO, verbose) {
    .Call(`_ProFAST_correct_one_gene`, Xlist, RList, HList, Tm, Adjlist, sigmaj_int, psij_int, alphaj_int, gammaj_int, zetaj_int, maxIter, epsELBO, verbose)
}

correct_genes <- function(XList, RList, HList, Tm, Adjlist, sigma_int, psi_int, alpha_int, gamma_int, zeta_int, maxIter, epsELBO, verbose) {
    .Call(`_ProFAST_correct_genes`, XList, RList, HList, Tm, Adjlist, sigma_int, psi_int, alpha_int, gamma_int, zeta_int, maxIter, epsELBO, verbose)
}

pdistance_cpp <- function(Ar, Br, eta = 1e-10) {
    .Call(`_ProFAST_pdistance_cpp`, Ar, Br, eta)
}

gene_embed_cpp <- function(X, ce_cell) {
    .Call(`_ProFAST_gene_embed_cpp`, X, ce_cell)
}

#' @keywords internal
#' @noRd
#' 
NULL

profast_g_cpp <- function(Xlist, Adjlist, nu_int, W_int, Lam_int, Psi_int, EvList, maxIter, epsLogLik, verbose, homo = FALSE, Psi_diag = FALSE) {
    .Call(`_ProFAST_profast_g_cpp`, Xlist, Adjlist, nu_int, W_int, Lam_int, Psi_int, EvList, maxIter, epsLogLik, verbose, homo, Psi_diag)
}

profast_p_cpp <- function(Xlist, AList, Adjlist, nv_int, W_int, Lam_int, Psi_int, EvList, maxIter, epsELBO, verbose, homo = FALSE, Psi_diag = TRUE) {
    .Call(`_ProFAST_profast_p_cpp`, Xlist, AList, Adjlist, nv_int, W_int, Lam_int, Psi_int, EvList, maxIter, epsELBO, verbose, homo, Psi_diag)
}

